package com.sinedrio.danai.senate.chat

import java.util.UUID

/**
 * A single message posted in a [ChatSession].
 *
 * @param id              Unique message identifier.
 * @param sessionId       The session this message belongs to.
 * @param senderId        Identifier of the sender (agent id, human id, or moderator constant).
 * @param senderName      Display name shown in the chat bubble.
 * @param senderPersona   Short persona label (e.g. "The Detective").
 * @param content         The text content of the message.
 * @param timestamp       Unix epoch millis when the message was created.
 * @param isHuman         `true` when the message was typed by the human moderator.
 * @param isAutoModerator `true` when the message was generated by the [AutoModerator].
 */
data class ChatMessage(
    val id: String = UUID.randomUUID().toString(),
    val sessionId: String,
    val senderId: String,
    val senderName: String,
    val senderPersona: String = "",
    val content: String,
    val timestamp: Long = System.currentTimeMillis(),
    val isHuman: Boolean = false,
    val isAutoModerator: Boolean = false
)
